### ISSUE TITLE
GameJolt_DataStorage_set issue

### ISSUE THREAD

**Issue by Se1d228** [YoYoGames/GMEXT-GameJolt#3]
I tried make save system, but game crashes with error
`ERROR in
action number 1
of Key Press Event for E-key Key
for object obj_save:

DoAdd :: Execution Error
 at gml_Script_Scr_GameJolt_Parameters (line 11) - 			str += "&"+string(argument[a]) + "=" + argument[a+1]
############################################################################################
gml_Script_Scr_GameJolt_Parameters (line 11)
gml_Script_GameJolt_DataStorage_Set (line 370) - 	url = Scr_GameJolt_Parameters(url,
gml_Object_obj_save_KeyPress_69 (line 3) - 	GameJolt_DataStorage_Set("coems", global.coems)`

Here is the code:
`e = 1
if(e == 1 && m = 1){
	GameJolt_DataStorage_Set("coems", global.coems)
	GameJolt_DataStorage_Set("doxscore", global.doxscore)
	GameJolt_DataStorage_Set("buff", global.buff)
	with(obj_savemon){
		alarm_set(0, 5)
		visible = true
	}
}`

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, you can attach it directly if it's something you are willing to share publicly, or upload via something like Google Drive so we can request access to keep it private. The ticket can then simply be re-opened.

We request a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!
